export type LipnoMapPointCategory = "sluzby" | "gastro" | "zazitky" | "doprava" | "ubytovani";

export type LipnoMapPoint = {
  id: string;
  code: string;
  title: string;
  category: LipnoMapPointCategory;
  x: number;
  y: number;
  summary: string;
  location: string;
  phone?: string;
  email?: string;
  openingHours: string[];
  href?: string;
  hrefLabel?: string;
};

export const lipnoMapImage = {
  src: "https://www.lipno.info/files/lipno/uploads/files/mapy/16784507401041-171-mapa-leto-2022.png",
  alt: "Mapa Rodinného areálu Lipno",
  width: 2000,
  height: 1464,
};

export const lipnoMapPoints: LipnoMapPoint[] = [
  {
    id: "kasa",
    code: "2",
    title: "Kasa",
    category: "sluzby",
    x: 72.1,
    y: 66.2,
    summary: "Hlavní pokladna a orientační bod v centrální části areálu.",
    location: "Centrální zóna Lipna",
    phone: "+420 731 410 800",
    email: "infocentrum@lipno.info",
    openingHours: ["Provoz dle aktuální otevírací doby areálu."],
    href: "/oteviraci-doby",
    hrefLabel: "Otevírací doby",
  },
  {
    id: "stezka",
    code: "11",
    title: "Stezka korunami stromů",
    category: "zazitky",
    x: 42.6,
    y: 48.3,
    summary: "Ikonický výjezd a hlavní cíl horní části areálu.",
    location: "Horní část Rodinného areálu Lipno",
    phone: "+420 601 509 116",
    email: "info@stezkakorunamistromu.cz",
    openingHours: ["Denně 10:00–17:00", "Poslední vstup 1 hodinu před koncem provozu."],
    href: "/zazitky/stezka-korunami-stromu",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "kralovstvi",
    code: "12",
    title: "Království lesa",
    category: "zazitky",
    x: 39.8,
    y: 35.8,
    summary: "Rodinná herní zóna v horní části areálu přímo pod Stezkou.",
    location: "Horní část areálu u Stezky",
    phone: "+420 601 509 116",
    email: "info@kralovstvilesa.cz",
    openingHours: ["Sezónní provoz jaro–podzim", "Běžně 10:00–18:00 až 19:00 dle části sezóny."],
    href: "/zazitky/kralovstvi-lesa",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "lanovka-express",
    code: "A",
    title: "Lanovka Lipno Express",
    category: "doprava",
    x: 51.8,
    y: 53.2,
    summary: "Hlavní vývoz od P1 ke Stezce, Království lesa i horním trasám.",
    location: "Centrální parkoviště P1",
    phone: "+420 731 410 800",
    email: "infocentrum@lipno.info",
    openingHours: ["Sezónní provoz dle oficiálních provozních dob", "V létě typicky od 9:45."],
    href: "/zazitky/lanove-drahy",
    hrefLabel: "Detail lanovek",
  },
  {
    id: "element-lakeside-apartments",
    code: "15",
    title: "Element Lakeside Apartments",
    category: "ubytovani",
    x: 86.9,
    y: 45.4,
    summary: "Apartmánové ubytování přímo u jezera v klidnější zóně areálu.",
    location: "Lakeside zóna u jezera",
    openingHours: ["Ubytování dle rezervačního režimu partnera."],
    href: "/ubytovani",
    hrefLabel: "Ubytování",
  },
  {
    id: "hotel-element",
    code: "H1",
    title: "Hotel Element",
    category: "ubytovani",
    x: 74.0,
    y: 60.5,
    summary: "Hotel v srdci areálu s pěší návazností na služby, gastro a lanovku.",
    location: "Centrální část areálu",
    href: "/ubytovani",
    hrefLabel: "Ubytování",
    openingHours: ["Celoroční hotelový provoz dle partnera."],
  },
  {
    id: "apartmany-element",
    code: "H2",
    title: "Apartmány Element",
    category: "ubytovani",
    x: 78.8,
    y: 46.8,
    summary: "Stylové apartmány přímo u vody pro delší rodinný pobyt.",
    location: "Lipno nad Vltavou, u jezera",
    href: "/ubytovani",
    hrefLabel: "Ubytování",
    openingHours: ["Ubytování dle rezervačního režimu partnera."],
  },
  {
    id: "camping-modrin-ubytovani",
    code: "13",
    title: "Camping Lipno Modřín",
    category: "ubytovani",
    x: 88.2,
    y: 71.2,
    summary: "Kemp u vody a cyklo-inline stezky v jižní části areálu.",
    location: "Camping Lipno Modřín",
    phone: "+420 731 410 803",
    email: "info@campinglipno.cz",
    href: "/ubytovani",
    hrefLabel: "Ubytování",
    openingHours: ["Hlavní provoz v letní sezóně."],
  },
  {
    id: "stodola",
    code: "R4",
    title: "Restaurace Stodola",
    category: "gastro",
    x: 74.8,
    y: 57.9,
    summary: "Hlavní restaurace v centrální části areálu, dobrá na oběd i večeři.",
    location: "Hotel Element, centrální zóna",
    phone: "+420 722 980 028",
    email: "restaurace@stodolalipno.cz",
    openingHours: ["Denně 11:00–23:00"],
    href: "/gastro/restaurace-stodola",
    hrefLabel: "Detail podniku",
  },
  {
    id: "povidlon",
    code: "R5",
    title: "Cukrárna Povidloň",
    category: "gastro",
    x: 76.2,
    y: 58.4,
    summary: "Káva, dezerty a celodenní sweet stop v srdci areálu.",
    location: "Lipno nad Vltavou 330",
    phone: "+420 722 990 506",
    email: "cukrarna@cukrarnapovidlon.cz",
    openingHours: ["Denně 8:00–19:00"],
    href: "/gastro/cukrarna-povidlon",
    hrefLabel: "Detail podniku",
  },
  {
    id: "kramec",
    code: "R3",
    title: "Bistro Kramec",
    category: "gastro",
    x: 38.4,
    y: 43.3,
    summary: "Bistro u horního náměstíčka a výstupu lanovky, silné hlavně v zimním provozu a aprés-ski rytmu.",
    location: "Horní náměstíčko u výstupu lanovky Lipno Express",
    openingHours: ["Provoz se řídí sezónou a akcemi areálu.", "Nejjistější kontrola přes kalendář a provoz areálu."],
    href: "https://www.lipno.info/kalendar/192-dj-ch4mba-bistro-kramec.html",
    hrefLabel: "Oficiální zmínka",
  },
  {
    id: "aquaworld",
    code: "19",
    title: "Aquaworld",
    category: "zazitky",
    x: 76.4,
    y: 42.8,
    summary: "Indoor bazén, sauna a jistota programu za horšího počasí.",
    location: "Lipno nad Vltavou 86",
    phone: "+420 720 483 007",
    email: "infocentrum@lipno.info",
    openingHours: ["Sezónní provoz dle období", "V létě obvykle 10:00–21:00."],
    href: "/zazitky/aquaworld-lipno",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "hopsarium",
    code: "20",
    title: "Hopsárium / Papilonia",
    category: "zazitky",
    x: 76.6,
    y: 45.5,
    summary: "Indoor rodinná jistota programu v centrální zóně u Aquaworldu.",
    location: "Centrální část Lipna",
    openingHours: ["Provoz dle aktuální sezóny a denního režimu."],
    href: "/aktivity",
    hrefLabel: "Aktivity",
  },
  {
    id: "lanovy-park",
    code: "17",
    title: "Lanový park",
    category: "zazitky",
    x: 71.2,
    y: 63.8,
    summary: "Lehce adrenalinová aktivita nad centrálním parkovištěm.",
    location: "Centrální část areálu u parkoviště P1",
    phone: "+420 607 426 502",
    email: "lanovypark@lipnoservis.cz",
    openingHours: ["Sezónní provoz jaro–podzim", "V létě typicky od 10:00 nebo 12:30 podle dne."],
    href: "/zazitky/lanovy-park",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "wakeboarding",
    code: "16",
    title: "Wakeboarding",
    category: "zazitky",
    x: 82.9,
    y: 72.0,
    summary: "Vodní sportovní bod v jižní části areálu směrem k Modřínu.",
    location: "Jižní část areálu u vody",
    openingHours: ["Silně sezónní letní provoz."],
    href: "/aktivity",
    hrefLabel: "Aktivity",
  },
  {
    id: "bobova-draha",
    code: "21",
    title: "Bobová dráha",
    category: "zazitky",
    x: 68.7,
    y: 67.2,
    summary: "Celoroční rodinná jistota programu za každého počasí.",
    location: "Centrální část areálu Lipno",
    phone: "+420 602 780 726",
    email: "info@slideland.cz",
    openingHours: ["Otevřeno každý den, 365 dní v roce.", "Denní režim drží provozovatel Slideland."],
    href: "/zazitky/bobova-draha",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "adventure-golf",
    code: "22",
    title: "Adventure golf",
    category: "zazitky",
    x: 96.2,
    y: 81.7,
    summary: "Rodinný doplňkový program v jižní části Lipna.",
    location: "Směr Frymburk / dolní část areálu",
    openingHours: ["Letní sezónní provoz."],
    href: "/aktivity",
    hrefLabel: "Aktivity",
  },
  {
    id: "beach-volleyball",
    code: "23",
    title: "Beach volleyball",
    category: "zazitky",
    x: 84.0,
    y: 49.4,
    summary: "Plážové hřiště v zóně u jezera a MOLO.",
    location: "Plážová zóna u jezera",
    openingHours: ["Volnější sezónní provoz podle počasí."],
    href: "/aktivity",
    hrefLabel: "Aktivity",
  },
  {
    id: "bikepark-trasy",
    code: "25",
    title: "Bikepark – trasy",
    category: "zazitky",
    x: 31.4,
    y: 25.1,
    summary: "Hlavní sjezdové a flow trasy v horní části kopce.",
    location: "Svah nad Kramolínem",
    href: "/zazitky/bikepark-lipno",
    hrefLabel: "Detail atrakce",
    openingHours: ["V návaznosti na letní provoz lanovky a bikeparku."],
  },
  {
    id: "sjezdove-kolobezky-trasa",
    code: "26",
    title: "Sjezdové koloběžky – trasa",
    category: "zazitky",
    x: 56.0,
    y: 38.1,
    summary: "Trasa navazující na půjčovnu a vývoz lanovkou.",
    location: "Horní až střední část areálu",
    href: "/pujcovny/sjezdove-kolobezky",
    hrefLabel: "Detail půjčovny",
    openingHours: ["V návaznosti na letní provoz půjčoven a lanovek."],
  },
  {
    id: "singletrack-trasa",
    code: "27",
    title: "Singletrack – rodinná cyklotrasa",
    category: "zazitky",
    x: 34.0,
    y: 28.0,
    summary: "Rodinný singletrack napojený na horní část areálu.",
    location: "Kramolín a navazující lesní část",
    href: "/pujcovny/singletrack-pujcovna",
    hrefLabel: "Detail půjčovny",
    openingHours: ["V návaznosti na letní cyklo provoz."],
  },
  {
    id: "disc-golf",
    code: "28",
    title: "Disc golf",
    category: "zazitky",
    x: 30.0,
    y: 39.0,
    summary: "Volnočasová sportovní aktivita v horní části areálu.",
    location: "Okolí horní části Kramolína",
    href: "/aktivity",
    hrefLabel: "Aktivity",
    openingHours: ["Volně přístupné dle sezóny a stavu areálu."],
  },
  {
    id: "naucna-stezka",
    code: "29",
    title: "Naučná stezka k ovčínu",
    category: "zazitky",
    x: 6.5,
    y: 34.8,
    summary: "Klidnější pěší trasa mimo hlavní těžiště rodinného areálu.",
    location: "Západní část mapy směrem k ovčínu",
    href: "/aktivity",
    hrefLabel: "Aktivity",
    openingHours: ["Volně přístupné."],
  },
  {
    id: "jezerni-cyklo-inline",
    code: "30",
    title: "Jezerní cyklo-inline stezka",
    category: "zazitky",
    x: 82.7,
    y: 63.5,
    summary: "Hlavní rovinný tah kolem jezera pro kola, brusle i rodinné přesuny.",
    location: "Jezerní promenáda a navazující stezka",
    href: "/kolemkolem",
    hrefLabel: "KolemKolem",
    openingHours: ["Celodenně přístupná trasa."],
  },
  {
    id: "marina",
    code: "14",
    title: "Přístav Marina Lipno",
    category: "zazitky",
    x: 76.2,
    y: 54.0,
    summary: "Výchozí bod pro jezero, MOLO zónu, plavby a část gastro nabídky.",
    location: "Lipno nad Vltavou, nábřeží u jezera",
    openingHours: ["Celodenně přístupná zóna", "Jednotlivé podniky v okolí mají vlastní provoz."],
  },
  {
    id: "molo",
    code: "R1",
    title: "MOLO Restaurant / Cafe du Lac",
    category: "gastro",
    x: 80.0,
    y: 47.0,
    summary: "Prémiovější gastro zóna nad jezerem s restaurací i designovou kavárnou.",
    location: "MOLO Lipno, Lipno nad Vltavou 517",
    phone: "+420 720 985 270",
    email: "restaurant@mololipno.cz",
    openingHours: ["MOLO Restaurant denně 12:00–22:00", "Cafe du Lac dle provozu MOLO Resort."],
    href: "/gastro",
    hrefLabel: "Zobrazit gastro",
  },
  {
    id: "beach-cafe",
    code: "R8",
    title: "Beach café",
    category: "gastro",
    x: 83.4,
    y: 44.2,
    summary: "Rychlá zastávka u vody a plážového provozu.",
    location: "Plážová zóna u jezera",
    openingHours: ["Silně sezónní letní provoz", "Přesný čas se mění podle počasí a návštěvnosti."],
    href: "/gastro",
    hrefLabel: "Gastro podniky",
  },
  {
    id: "modrin",
    code: "R7",
    title: "Restaurace Modřín / Grill Modřín",
    category: "gastro",
    x: 81.0,
    y: 68.6,
    summary: "Gastro bod u kempu a cyklo-inline stezky směrem na Modřín.",
    location: "Camping Lipno Modřín",
    phone: "+420 731 410 803",
    email: "info@campinglipno.cz",
    openingHours: ["Provoz navázaný na kemp a hlavní sezónu.", "Aktuální režim je vhodné ověřit přes oficiální web kempu."],
    href: "https://www.lipno.info/zazitky/camping-lipno-modrin.html",
    hrefLabel: "Oficiální detail",
  },
  {
    id: "sjezdove-kolobezky-pujcovna",
    code: "6",
    title: "INTERSPORT Rent – Sjezdové koloběžky",
    category: "sluzby",
    x: 36.5,
    y: 54.0,
    summary: "Půjčovna sjezdových koloběžek navázaná na horní část areálu a trasy.",
    location: "Horní část areálu u lanovky",
    phone: "+420 731 656 154",
    openingHours: ["Sezónní letní provoz v návaznosti na lanovky."],
    href: "/pujcovny/sjezdove-kolobezky",
    hrefLabel: "Detail půjčovny",
  },
  {
    id: "kapitanat",
    code: "7",
    title: "INTERSPORT Rent Kapitanát",
    category: "sluzby",
    x: 79.4,
    y: 58.4,
    summary: "Silný nástupní bod pro kola, inline a část vodního vybavení.",
    location: "Kapitanát, u jezera",
    phone: "+420 731 656 154",
    openingHours: ["Letní půjčovna dle provozu areálu", "Online rezervace bývá zvýhodněná."],
    href: "/pujcovny/singletrack-pujcovna",
    hrefLabel: "Detail půjčovny",
  },
  {
    id: "plaz-pujcovna",
    code: "8",
    title: "INTERSPORT Rent – Pláž",
    category: "sluzby",
    x: 78.5,
    y: 48.2,
    summary: "Plážová půjčovna vodního vybavení u hlavní zóny jezera.",
    location: "Pláž u jezera",
    phone: "+420 731 410 813",
    openingHours: ["Hlavní letní provoz dle počasí a sezóny."],
    href: "/pujcovny/vodni-plavidla",
    hrefLabel: "Detail půjčovny",
  },
  {
    id: "beacharena-plavidla",
    code: "9",
    title: "INTERSPORT Rent – Beacharena",
    category: "sluzby",
    x: 87.4,
    y: 49.8,
    summary: "Výdejní bod vodních plavidel v Beach aréně.",
    location: "Beach aréna u jezera",
    phone: "+420 731 410 813",
    openingHours: ["Hlavní letní provoz dle počasí a sezóny."],
    href: "/pujcovny/vodni-plavidla",
    hrefLabel: "Detail půjčovny",
  },
  {
    id: "modrin-plavidla",
    code: "10",
    title: "INTERSPORT Rent – Modřín",
    category: "sluzby",
    x: 92.1,
    y: 69.5,
    summary: "Jižní výdejní bod vodních plavidel v kempu Modřín.",
    location: "Camping Lipno Modřín",
    phone: "+420 731 410 813",
    openingHours: ["Hlavní letní provoz dle počasí a sezóny."],
    href: "/pujcovny/vodni-plavidla",
    hrefLabel: "Detail půjčovny",
  },
  {
    id: "element",
    code: "5",
    title: "INTERSPORT Element",
    category: "sluzby",
    x: 75.7,
    y: 62.3,
    summary: "Prodejna, bikepark půjčovna a servis v centrální části areálu.",
    location: "Element u Restaurace Stodola",
    phone: "+420 731 656 154",
    openingHours: ["Sezónní provoz podle areálu", "Navazuje na bikepark a letní pohyb resortu."],
    href: "/pujcovny/bikepark-pujcovna",
    hrefLabel: "Detail půjčovny",
  },
];

export function getLipnoMapPointById(id: string) {
  return lipnoMapPoints.find((item) => item.id === id);
}
