export type LipnoMapPointCategory = "sluzby" | "gastro" | "zazitky" | "doprava";

export type LipnoMapPoint = {
  id: string;
  code: string;
  title: string;
  category: LipnoMapPointCategory;
  x: number;
  y: number;
  summary: string;
  location: string;
  phone?: string;
  email?: string;
  openingHours: string[];
  href?: string;
  hrefLabel?: string;
};

export const lipnoMapImage = {
  src: "https://www.lipno.info/files/lipno/uploads/files/mapy/16784507401041-171-mapa-leto-2022.png",
  alt: "Mapa Rodinného areálu Lipno",
  width: 2000,
  height: 1464,
};

export const lipnoMapPoints: LipnoMapPoint[] = [
  {
    id: "stezka",
    code: "11",
    title: "Stezka korunami stromů",
    category: "zazitky",
    x: 42.6,
    y: 48.3,
    summary: "Ikonický výjezd a hlavní cíl horní části areálu.",
    location: "Horní část Rodinného areálu Lipno",
    phone: "+420 601 509 116",
    email: "info@stezkakorunamistromu.cz",
    openingHours: ["Denně 10:00–17:00", "Poslední vstup 1 hodinu před koncem provozu."],
    href: "/zazitky/stezka-korunami-stromu",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "kralovstvi",
    code: "12",
    title: "Království lesa",
    category: "zazitky",
    x: 39.8,
    y: 35.8,
    summary: "Rodinná herní zóna v horní části areálu přímo pod Stezkou.",
    location: "Horní část areálu u Stezky",
    phone: "+420 601 509 116",
    email: "info@kralovstvilesa.cz",
    openingHours: ["Sezónní provoz jaro–podzim", "Běžně 10:00–18:00 až 19:00 dle části sezóny."],
    href: "/zazitky/kralovstvi-lesa",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "lanovka-express",
    code: "A",
    title: "Lanovka Lipno Express",
    category: "doprava",
    x: 51.8,
    y: 53.2,
    summary: "Hlavní vývoz od P1 ke Stezce, Království lesa i horním trasám.",
    location: "Centrální parkoviště P1",
    phone: "+420 731 410 800",
    email: "infocentrum@lipno.info",
    openingHours: ["Sezónní provoz dle oficiálních provozních dob", "V létě typicky od 9:45."],
    href: "/zazitky/lanove-drahy",
    hrefLabel: "Detail lanovek",
  },
  {
    id: "stodola",
    code: "R4",
    title: "Restaurace Stodola",
    category: "gastro",
    x: 74.8,
    y: 57.9,
    summary: "Hlavní restaurace v centrální části areálu, dobrá na oběd i večeři.",
    location: "Hotel Element, centrální zóna",
    phone: "+420 722 980 028",
    email: "restaurace@stodolalipno.cz",
    openingHours: ["Denně 11:00–23:00"],
    href: "/gastro/restaurace-stodola",
    hrefLabel: "Detail podniku",
  },
  {
    id: "povidlon",
    code: "R5",
    title: "Cukrárna Povidloň",
    category: "gastro",
    x: 76.2,
    y: 58.4,
    summary: "Káva, dezerty a celodenní sweet stop v srdci areálu.",
    location: "Lipno nad Vltavou 330",
    phone: "+420 722 990 506",
    email: "cukrarna@cukrarnapovidlon.cz",
    openingHours: ["Denně 8:00–19:00"],
    href: "/gastro/cukrarna-povidlon",
    hrefLabel: "Detail podniku",
  },
  {
    id: "kramec",
    code: "R3",
    title: "Bistro Kramec",
    category: "gastro",
    x: 38.4,
    y: 43.3,
    summary: "Bistro u horního náměstíčka a výstupu lanovky, silné hlavně v zimním provozu a aprés-ski rytmu.",
    location: "Horní náměstíčko u výstupu lanovky Lipno Express",
    openingHours: ["Provoz se řídí sezónou a akcemi areálu.", "Nejjistější kontrola přes kalendář a provoz areálu."],
    href: "https://www.lipno.info/kalendar/192-dj-ch4mba-bistro-kramec.html",
    hrefLabel: "Oficiální zmínka",
  },
  {
    id: "aquaworld",
    code: "19",
    title: "Aquaworld",
    category: "zazitky",
    x: 76.4,
    y: 42.8,
    summary: "Indoor bazén, sauna a jistota programu za horšího počasí.",
    location: "Lipno nad Vltavou 86",
    phone: "+420 720 483 007",
    email: "infocentrum@lipno.info",
    openingHours: ["Sezónní provoz dle období", "V létě obvykle 10:00–21:00."],
    href: "/zazitky/aquaworld-lipno",
    hrefLabel: "Detail atrakce",
  },
  {
    id: "marina",
    code: "14",
    title: "Přístav Marina Lipno",
    category: "zazitky",
    x: 76.2,
    y: 54.0,
    summary: "Výchozí bod pro jezero, MOLO zónu, plavby a část gastro nabídky.",
    location: "Lipno nad Vltavou, nábřeží u jezera",
    openingHours: ["Celodenně přístupná zóna", "Jednotlivé podniky v okolí mají vlastní provoz."],
  },
  {
    id: "molo",
    code: "R1",
    title: "MOLO Restaurant / Cafe du Lac",
    category: "gastro",
    x: 80.0,
    y: 47.0,
    summary: "Prémiovější gastro zóna nad jezerem s restaurací i designovou kavárnou.",
    location: "MOLO Lipno, Lipno nad Vltavou 517",
    phone: "+420 720 985 270",
    email: "restaurant@mololipno.cz",
    openingHours: ["MOLO Restaurant denně 12:00–22:00", "Cafe du Lac dle provozu MOLO Resort."],
    href: "/gastro",
    hrefLabel: "Zobrazit gastro",
  },
  {
    id: "beach-cafe",
    code: "R8",
    title: "Beach café",
    category: "gastro",
    x: 83.4,
    y: 44.2,
    summary: "Rychlá zastávka u vody a plážového provozu.",
    location: "Plážová zóna u jezera",
    openingHours: ["Silně sezónní letní provoz", "Přesný čas se mění podle počasí a návštěvnosti."],
    href: "/gastro",
    hrefLabel: "Gastro podniky",
  },
  {
    id: "modrin",
    code: "R7",
    title: "Restaurace Modřín / Grill Modřín",
    category: "gastro",
    x: 81.0,
    y: 68.6,
    summary: "Gastro bod u kempu a cyklo-inline stezky směrem na Modřín.",
    location: "Camping Lipno Modřín",
    phone: "+420 731 410 803",
    email: "info@campinglipno.cz",
    openingHours: ["Provoz navázaný na kemp a hlavní sezónu.", "Aktuální režim je vhodné ověřit přes oficiální web kempu."],
    href: "https://www.lipno.info/zazitky/camping-lipno-modrin.html",
    hrefLabel: "Oficiální detail",
  },
  {
    id: "kapitanat",
    code: "7",
    title: "INTERSPORT Rent Kapitanát",
    category: "sluzby",
    x: 79.4,
    y: 58.4,
    summary: "Silný nástupní bod pro kola, inline a část vodního vybavení.",
    location: "Kapitanát, u jezera",
    phone: "+420 731 656 154",
    openingHours: ["Letní půjčovna dle provozu areálu", "Online rezervace bývá zvýhodněná."],
    href: "/pujcovny/singletrack-pujcovna",
    hrefLabel: "Detail půjčovny",
  },
  {
    id: "element",
    code: "5",
    title: "INTERSPORT Element",
    category: "sluzby",
    x: 75.7,
    y: 62.3,
    summary: "Prodejna, bikepark půjčovna a servis v centrální části areálu.",
    location: "Element u Restaurace Stodola",
    phone: "+420 731 656 154",
    openingHours: ["Sezónní provoz podle areálu", "Navazuje na bikepark a letní pohyb resortu."],
    href: "/pujcovny/bikepark-pujcovna",
    hrefLabel: "Detail půjčovny",
  },
];

export function getLipnoMapPointById(id: string) {
  return lipnoMapPoints.find((item) => item.id === id);
}
